name: build-and-package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Publish PrismBot
        run: dotnet publish PrismBot -c Release -o osx-x64 -r osx-x64 --no-self-contained

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PrismBot-osx-x64-release
          path: osx-x64
