name: build-and-package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: [ "win-x64", "osx-x64", "linux-x64", "linux-arm64", "linux-arm" ]
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Publish PrismBot
        run: dotnet publish PrismBot -c Release -o ${{ matrix.arch }} -r ${{ matrix.arch }} --no-self-contained

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PrismBot-${{ matrix.arch }}-release
          path: ${{ matrix.arch }}
